export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_EMPTY = 'SEARCH_EMPTY';

export const NOMINATED_STARTED = 'NOMINATED_STARTED';
export const NOMINATED_SUCCESS = 'NOMINATED_SUCCESS';
export const NOMINATED_FAILED = 'NOMINATED_FAILED';
export const NOMINATED_ALREADY = 'NOMINATED_ALREADY';
export const NOMINATION_CANCELED = 'NOMINATION_CANCELED';
export const NOMINATIONS_COMPLETED = 'NOMINATIONS_COMPLETED';
export const NOMINATIONS_STORED = 'NOMINATIONS_STORED';
export const NOMINATIONS_CLEARED = 'NOMINATIONS_CLEARED';

export const WINNER_AUTH = 'WINNER_AUTH';
