export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_REMOVE_ERROR_MESSAGE = 'SEARCH_REMOVE_ERROR_MESSAGE';