export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_EMPTY = 'SEARCH_EMPTY';

export const NOMINATED_STARTED = 'NOMINATED_STARTED';
export const NOMINATED_SUCCESS = 'NOMINATED_SUCCESS';
export const NOMINATED_FAILED = 'NOMINATED_FAILED';
export const NOMINATED_ALREADY = 'NOMINATED_ALREADY';